eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  datasource:
     name: dev
     url: jdbc:mysql://192.168.1.134:3306/snailmall
     username: root
     password: peak123456
redis:
    host: localhost
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
